version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
      - ./data-source:/app/data-source
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001

  mlflow:
    image: python:3.10-slim
    command: >
      bash -c "pip install mlflow && mlflow server
      --host 0.0.0.0
      --port 5001
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlartifacts"
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts
